### ISSUE TITLE
关于ajax跨域问题

### ISSUE THREAD

**Issue by GrubbyHunter** [i5ting/imove#100]
由于是在线的项目，我们测试的接口通常可定不是在localhost:8080下的，如果我写了一个接口全路径，然后在localhost:8080下axios发起请求就会跨

**Comment by SmallStoneSK** [comment]
@GrubbyHunter 你说的跨域是哪个请求？

**Comment by iceytea** [comment]
两种解决方案：
1. 本地开发时配置反向代理。如果说imove有提供这种反向代理配置，就会方便一点
2. 针对接口放开跨域限制。

话说这个和imove没啥关系吧

**Comment by iceytea** [comment]
三种解决方案：
1. 本地开发时配置反向代理。如果说 imove 有提供这种反向代理配置，就会方便一点
2. 针对接口放开跨域限制。
3. 装一个 CORS 浏览器插件

话说这个问题和 imove 没啥关系吧
